version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    hostname: redis-server

  status-page:
    build: .
    container_name: status-page
    restart: "no"  # Prevents auto-restarting after script runs
    depends_on:
      - redis
    networks:
      - mynetwork
    environment:
      REDIS_HOST: redis-server
    ports:
      - "8000:8000"
      - "8001:8001"
    hostname: status-page-server
    command: >
      /bin/bash -c "
      echo 'Running upgrade.sh...' &&
      bash /opt/upgrade.sh &&
      source /opt/venv/bin/activate &&
      gunicorn --bind 0.0.0.0:8000 statuspage.wsgi:application --chdir /opt/statuspage --workers 3 --log-level debug
      "





networks:
  mynetwork:
    driver: bridge