version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    hostname: redis-server

  status-page:
    build: .
    container_name: status-page
    depends_on:
      - redis
    networks:
      - mynetwork
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      REDIS_HOST: redis-server

networks:
  mynetwork:
    driver: bridge
