apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page
  namespace: status-page
  labels:
    app: status-page
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: status-page
  template:
    metadata:
      labels:
        app: status-page
    spec:
      containers:
      - name: status-page
        image: status-page:latest  # Replace with your image
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: elasticache-secret
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: elasticache-secret
              key: REDIS_PORT
        envFrom:
        - configMapRef:
            name: status-page-config
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 20
