apiVersion: v1
kind: Service
metadata:
  name: status-page-service
  namespace: status-page
spec:
  selector:
    app: status-page
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: gunicorn
    port: 8001
    targetPort: 8001
  type: LoadBalancer
