name: Deploy Status-Page to AWS ECR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - opt/**
      - .github/**

permissions:
  contents: write

env:
  ECR_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ vars.ECR_REPOSITORY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: lets-play

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          curl -SL https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          python -m pip install --upgrade pip

      - name: Start Containers with Docker Compose
        run: |
          docker-compose up --build -d

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker image
        run: |
          docker tag status-page:latest $ECR_URL:$IMAGE_TAG
          docker push $ECR_URL:$IMAGE_TAG

  update_manifest:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    - name: Checkout lets-play branch
      uses: actions/checkout@v4
      with:
        ref: lets-play
        fetch-depth: 0  # Needed to push new branches

    - name: Update Kubernetes Manifest with new image tag
      run: |
        ECR_URL="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ vars.ECR_REPOSITORY }}"
        IMAGE_TAG="${{ github.sha }}"

        git config user.name github-actions
        git config user.email github-actions@github.com

        git checkout -b manifest_update

        echo "ECR_URL=${ECR_URL}"
        echo "IMAGE_TAG=${IMAGE_TAG}"

        sed -i "s|image: <IMAGE_FROM_ECR>|image: ${ECR_URL}:${IMAGE_TAG}|g" k8s_resources/statuspage/statuspage-deployment.yml

        git add k8s_resources/statuspage/statuspage-deployment.yml
        git commit -m "Update image tag to ${IMAGE_TAG}" || echo "No changes to commit"
        git push origin manifest_update

